Geração de DACTE
Engenere/BrazilFiscalReport pull request #23
Opened 2024-07-17 19:09 UTC by CristianoMafraJunior

## Objetivo

Implementar a geração de DACTE a partir do CT-e, incluindo:

- QR Code
- Recibo
- Detalhes da transportadora
- Informações do tomador do serviço
- Informações do produto transportado

## Status

Em desenvolvimento.

2024-07-19 17:50 UTC, antoniospneto requested changes
É preciso verificar o qrcorde, pois a leitura está retornando um valor errado.

2024-07-19 18:32 UTC, antoniospneto requested changes
Mapear os dados para popular os quadro expedidor e recebedor

2024-07-22 13:02 UTC, antoniospneto commented
![image](https://github.com/user-attachments/assets/124ecf0f-07ea-4a29-bb99-03e2364f192f)

Falta incluir os outros tipos de tomador:

0-Remetente;
1-Expedidor;
2-Recebedor;
3-Destinatário;
4-Outro

![image](https://github.com/user-attachments/assets/a78171fe-e8bf-4ff9-8e6c-81d963b44520)

2024-07-24 12:25 UTC, CristianoMafraJunior commented
> Mapear os dados para populares os quadros expedidor e recebedor

2024-08-02 17:22 UTC, antoniospneto commented on brazilfiscalreport/dacte/dacte.py
> +        # TODO - TESTE
verificar se ainda é necessario

2024-08-02 17:24 UTC, antoniospneto commented on brazilfiscalreport/dacte/dacte.py
> +        ):  # TODO Arrumar a sopreposição do title: NOME E VALOR SOBRE o FPESO
esse ainda está pendente?

2024-08-03 00:32 UTC, antoniospneto approved these changes

2024-10-24 17:21 UTC, antoniospneto commented on brazilfiscalreport/dacte/dacte_conf.py
> +}
Esses por ser constantes deveriam ser em caixa alta

2024-10-24 17:59 UTC, merged